### ISSUE TITLE
Create new Card component

### ISSUE THREAD

**Issue by diondiondion** [5app/base5-ui#103]
We're currently using two different Card components in the dashboard repo: `ui/elements/Card` and `ui/elements/Card/legacy` ("LegacyCard").

These should be replaced by a single, lower-level Card component that can handle all necessary use cases. The component should be built on top of `Box`.

**Changes:**
- The distinction between "panels" and "cards" should be removed, instead the border radius should be controllable per card, and theme sections might gain a new optional `backgroundAlt` property for alternating background colours when Cards are nested.
- One important change will have to be the "inverted" colour mode, which shouldn't be hard-coded the way it currently is in `LegacyCard`, but should be a new theme section instead (it can be added to the 5app theme and all other themes will inherit it). This will make sure that links and other elements placed in an inverted card will be readable.
- The margin declarations that are added to the current `Card` component when a `maxWidth` is defined should be removed, they'll be able to be added on a case-by-case basis

**Comment by diondiondion** [comment]
QA: This is mostly an internal refactoring, however some small visual differences were introduced which should be intentional unless they cause obvious UX or design issues such as boxes missing their background colour, or bad readability of text in boxes.

**Comment by SanjanaKampati** [comment]
Retested the ticket on staging environment using url:https://zenq-staging.fiveapp.com and observed the following

**[QA Passed]**

1.Background color, check boxes, text in boxes and menu dropdowns are displayed as expected in all the browsers(IE:11,Chrome:83,Firefox,Edge and safari)


![14328stag.gif](https://zube.io/files/5app/e417825b2813f9c2a101626b36607e93-14328stag.gif)
