### ISSUE TITLE
Menu/NavMenu/Select: "popover.update is not a function" when opening menu

### ISSUE THREAD

**Issue by diondiondion** [5app/base5-ui#115]

**Comment by diondiondion** [comment]
QA note:
This fixes an issue that's not user-facing and can only be observed if the browser's Console panel is opened. Opening any dropdown menus should now **not** show a `popover.update is not a function` error anymore.

Can you please also check whether the "Add button menu" can get stuck in a semi-transparent state in IE11, as seen below?

![image.png](https://zube.io/files/5app/cd32e8d5935789e7eaa8998488af9cb8-image.png)

I could only reproduce this in IE11 on BrowserStack, but it might just be a BrowserStack issue.

**Comment by PalaniNadimpalli** [comment]
Retested the ticket in dev environment using url:https://zenq-dev.fiveapp.com and observed the following

**[QA Passed]**

Semi-transparent is not displayed when selected drop down menus for the following functionalities.

Your hub:
1.Account icon drop down menu
2.User settings page

Admin dashboard:
1.Asset Library Page
2.Playlist page
3.Users page
4.Topics page
5.Settings -Asset audit , Message audit


![dropdownmenu.gif](https://zube.io/files/5app/d838f98fabdb5486332bbdb4955b1cac-dropdownmenu.gif)

**Comment by PalaniNadimpalli** [comment]
Retested the ticket against Staging environment with url:https://zenq-staging.fiveapp.com and observed the following.

**[QA Passed]**

Semi-transparent is not displayed when clicked on the Drop down menus in the following functionalities,

**Your Hub:**
Account icon
My Teams 
User Settings Page 

**Admin Dashboard:**
Asset library
Playlist page 
Topics Page 
Users page 
Settings - Asset audit, message audit 





![14740.gif](https://zube.io/files/5app/b38b032eb3c251b93ae47f3d8affc3e4-14740.gif)
