### ISSUE TITLE
Use smaller colour manipulation library

### ISSUE THREAD

**Issue by diondiondion** [5app/base5-ui#120]
Chroma JS weighs in at 13.7 kB, while there are smaller libraries like https://color2k.com that weigh less than 3 kB. Look into whether the API of the latter is equally capable and switch over if so.

**Comment by diondiondion** [comment]
This is a "behind the scenes" refactor and should not result in any visual changes. A regular regression test should cover any potential issues.

**Comment by SanjanaKampati** [comment]
We have completed half regression and observed no visual changes in the application. Hence moving the ticket to QA Passed
