### ISSUE TITLE
usePopoverState: Built-in option for closing popover on Esc keypress

### ISSUE THREAD

**Issue by diondiondion** [5app/base5-ui#96]
Popovers must be dismissible via the <kbd>Esc</kbd> key, this should be built into the `usePopoverState` hook, possibly through combining it with the `useEventListener` hook. An initial implementation of this was buggy & I worked around it using the `DocumentClickListener` component, but a hook-only solution would be preferable. `useEventListener` probably needs a proper way to disable it.

**Comment by diondiondion** [comment]
QA: All tooltips and dropdown menus in the hub and the admin dashboard should now be dismissible by pressing the <kbd>Esc</kbd> key.

**Comment by PalaniNadimpalli** [comment]
Retested the ticket on dev environment using url:https://zenq-dev.fiveapp.com and observed the following.

**[QA Passed]**

-Account icon dropdown,Profile page and tooltips under my teams(asset progress page and playlist progress page) is dismissed when 'ESC' key is pressed.

**[QA Failed]**

-Dropdowns and tool tips are not dismissed when 'ESC'key is pressed in Admin dashboard.


![13773dev.gif](https://zube.io/files/5app/46899432072ddf205f79dd1ca3ef7086-13773dev.gif)

**Comment by diondiondion** [comment]
HI @PalaniNadimpalli , thank you for testing this. I can't reproduce the failed scenario in Chrome, can you please clear your cache, reload the page, and try again? It's possible that the latest changes hadn't come through in that browser tab yet when you were testing it.

**Comment by PalaniNadimpalli** [comment]
@diondiondion : Issue is in IE11 browser. When we retest a ticket we check in IE11 browser

**Comment by PalaniNadimpalli** [comment]
Retested the ticket on dev environment using url:https://zenq-dev.fiveapp.com and observed the following.

**[QA Passed]**

Tooltips and Dropdown menus are dismissed when 'ESC'key is pressed in the functionalities of Admin dashboard and Your hub(Profile,asset progress,playlist progress page and account icon dropdown).
Observed in IE:11 and Chrome:83.0 browsers.


![13773mod in dev.gif](https://zube.io/files/5app/a9dd042a509215590bd8b0d3ae03d714-13773mod-in-dev.gif)

**Comment by PalaniNadimpalli** [comment]
Retested the ticket on dev environment using url:https://zenq-dev.fiveapp.com and observed the following.

[QA Passed]:

Tooltips and Dropdown menus are dismissed when 'ESC'key is pressed in Admin dashboard and Your hub

Observed in IE:11 and Chrome:83.0 browsers.

**Comment by PalaniNadimpalli** [comment]
Retested the ticket on staging environment using url:https://zenq-staging.fiveapp.com and observed the following.

**[QA Passed]**

Tooltips and Dropdown menus are dismissed when 'ESC'key is pressed in Admin dashboard and Your hub.

**[Observation]**

Rectangle border and terminator/action border is displayed for some of the dropdown menus When Esc key is pressed in admin dashboard and your hub. 

Observed in chrome and IE browsers.

![13773stag...gif](https://zube.io/files/5app/7b5e4798e7b352f686131f798efa0b01-13773stag-.gif)

**Comment by diondiondion** [comment]
> Rectangle border and terminator/action border is displayed for some of the dropdown menus When Esc key is pressed in admin dashboard and your hub.

That's expected behaviour. When a dropdown menu is closed, keyboard focus must be returned to the element that opened the menu. The focus indicator appears only when using the keyboard, so when <kbd>Esc</kbd> is used to close a dropdown menu, it becomes visible.

**Comment by PalaniNadimpalli** [comment]
@diondiondion : Thanks for the confirmation. As it is expected moving to QA Passed
